pipeline {
    agent any
    environment {
        RELEASE='20.04'
    }
    stages {
        
        stage('Build') {
            environment{
                LOG_LEVEL='INFO'
            }
             parallel {
               stage('machine1') {
                 steps{
                   echo "Building release ${RELEASE} for ${STAGE_NAME} with log level ${LOG_LEVEL}
                 }
               }
               stage('machine2') {
                 steps{
                   echo "Building release ${RELEASE} for ${STAGE_NAME} with log level ${LOG_LEVEL}
                 }
               }
               stage('machine3') {
                 steps{
                   echo "Building release ${RELEASE} for ${STAGE_NAME} with log level ${LOG_LEVEL}
                 }
               }
           }
         }
        stage('Test') {
            steps {
                echo "Testing. I can see release ${RELEASE}..."
            }
        }
        
      stage('Deploy') {
        input {
          message 'Deploy?'
          ok 'Do it!'
          parameters {
            string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment environment')          
          }
         }
        steps {
          echo "Deplying release ${RELEASE} to environment ${TARGET_ENVIRONMENT}"
        }
      }
    }
  post {
    always {
      echo 'Prints always failing or not'
    }
  }
}
